/**
 * Author......: Generated by hashcat
 * License.....: MIT
 */

 #include "common.h"
 #include "types.h"
 #include "modules.h"
 #include "bitops.h"
 #include "convert.h"
 #include "shared.h"
 #include "memory.h"
 
static const u32   ATTACK_EXEC    = ATTACK_EXEC_OUTSIDE_KERNEL;
static const u32   DGST_POS0      = 0;
static const u32   DGST_POS1      = 1;
static const u32   DGST_POS2      = 2;
static const u32   DGST_POS3      = 3;
static const u32   DGST_SIZE      = DGST_SIZE_4_4;
static const u32   HASH_CATEGORY  = HASH_CATEGORY_FDE;
static const char *HASH_NAME      = "ZFS encryption (PBKDF2-HMAC-SHA256 + AES-256-GCM)";
static const u64   KERN_TYPE      = 26666;
static const u32   OPTI_TYPE      = OPTI_TYPE_ZERO_BYTE
                                  | OPTI_TYPE_SLOW_HASH_SIMD_LOOP;
static const u64   OPTS_TYPE      = OPTS_TYPE_STOCK_MODULE
                                  | OPTS_TYPE_PT_GENERATE_LE;
static const u32   SALT_TYPE      = SALT_TYPE_EMBEDDED;
static const char *ST_PASS        = "hashcat";
static const char *ST_HASH        = "$zfs$1*350000*cfb3a5f3*ee96a312f27d6f7d90c6b92c2161684d*748c8a5a0d363d5a*bb83d28b874348abce7fe123a2401abbd64d2c79df2397e3d7302081f2c56365*92*41959b311d9e84844661821c*1*8*cbc134f57a75a0accd5eb326e6ffb7bf4197e09816717537c8c1c07ff9aaac7f1b83b74bebc461629c6e1e8d99b79fd4c7c7f6d212d8e094c97be62d343029d5";
//$zfs$VERSION*ITERATIONS*SALT*MAC*GUID*MASTER_KEY*DDOBJ*IV*REFCOUNT*SUITE*HMAC_KEY
u32         module_attack_exec    (MAYBE_UNUSED const hashconfig_t *hashconfig, MAYBE_UNUSED const user_options_t *user_options, MAYBE_UNUSED const user_options_extra_t *user_options_extra) { return ATTACK_EXEC;     }
u32         module_dgst_pos0      (MAYBE_UNUSED const hashconfig_t *hashconfig, MAYBE_UNUSED const user_options_t *user_options, MAYBE_UNUSED const user_options_extra_t *user_options_extra) { return DGST_POS0; }
u32         module_dgst_pos1      (MAYBE_UNUSED const hashconfig_t *hashconfig, MAYBE_UNUSED const user_options_t *user_options, MAYBE_UNUSED const user_options_extra_t *user_options_extra) { return DGST_POS1; }
u32         module_dgst_pos2      (MAYBE_UNUSED const hashconfig_t *hashconfig, MAYBE_UNUSED const user_options_t *user_options, MAYBE_UNUSED const user_options_extra_t *user_options_extra) { return DGST_POS2; }
u32         module_dgst_pos3      (MAYBE_UNUSED const hashconfig_t *hashconfig, MAYBE_UNUSED const user_options_t *user_options, MAYBE_UNUSED const user_options_extra_t *user_options_extra) { return DGST_POS3; }
u32         module_dgst_size      (MAYBE_UNUSED const hashconfig_t *hashconfig, MAYBE_UNUSED const user_options_t *user_options, MAYBE_UNUSED const user_options_extra_t *user_options_extra) { return DGST_SIZE; }
u32         module_hash_category  (MAYBE_UNUSED const hashconfig_t *hashconfig, MAYBE_UNUSED const user_options_t *user_options, MAYBE_UNUSED const user_options_extra_t *user_options_extra) { return HASH_CATEGORY; }
const char *module_hash_name      (MAYBE_UNUSED const hashconfig_t *hashconfig, MAYBE_UNUSED const user_options_t *user_options, MAYBE_UNUSED const user_options_extra_t *user_options_extra) { return HASH_NAME; }
u64         module_kern_type      (MAYBE_UNUSED const hashconfig_t *hashconfig, MAYBE_UNUSED const user_options_t *user_options, MAYBE_UNUSED const user_options_extra_t *user_options_extra) { return KERN_TYPE; }
u32         module_opti_type      (MAYBE_UNUSED const hashconfig_t *hashconfig, MAYBE_UNUSED const user_options_t *user_options, MAYBE_UNUSED const user_options_extra_t *user_options_extra) { return OPTI_TYPE; }
u64         module_opts_type      (MAYBE_UNUSED const hashconfig_t *hashconfig, MAYBE_UNUSED const user_options_t *user_options, MAYBE_UNUSED const user_options_extra_t *user_options_extra) { return OPTS_TYPE; }
u32         module_salt_type      (MAYBE_UNUSED const hashconfig_t *hashconfig, MAYBE_UNUSED const user_options_t *user_options, MAYBE_UNUSED const user_options_extra_t *user_options_extra) { return SALT_TYPE; }
const char *module_st_hash        (MAYBE_UNUSED const hashconfig_t *hashconfig, MAYBE_UNUSED const user_options_t *user_options, MAYBE_UNUSED const user_options_extra_t *user_options_extra) { return ST_HASH; }
const char *module_st_pass        (MAYBE_UNUSED const hashconfig_t *hashconfig, MAYBE_UNUSED const user_options_t *user_options, MAYBE_UNUSED const user_options_extra_t *user_options_extra) { return ST_PASS; }
u32 module_pw_min (MAYBE_UNUSED const hashconfig_t *hashconfig, MAYBE_UNUSED const user_options_t *user_options, MAYBE_UNUSED const user_options_extra_t *user_options_extra)
{
  const u32 pw_min = 8;

  return pw_min;
}

u32 module_pw_max (MAYBE_UNUSED const hashconfig_t *hashconfig, MAYBE_UNUSED const user_options_t *user_options, MAYBE_UNUSED const user_options_extra_t *user_options_extra)
{
  // this overrides the reductions of PW_MAX in case optimized kernel is selected
  // IOW, even in optimized kernel mode it support length 256

  const u32 pw_max = PW_MAX;

  return pw_max;
}


int hex_to_u32_buffer (const u8 *hex, u32 *buf, int u32_count)
{
  for (int i = 0; i < u32_count; i++)
  {
    u32 val = 0;

    for (int j = 0; j < 4; j++) // 4 bytes per u32 (i.e., 8 hex chars)
    {
      const u8 *p = &hex[i * 8 + j * 2]; // 2 hex chars per byte
      u8 byte = hex_to_u8(p);           // assume hex_to_u8 parses 2 hex chars to a byte
      val = (val << 8) | byte;          // big-endian
    }

    buf[i] = val;
  }

  return 0;
}


typedef struct pbkdf2_sha1_tmp {
  u32  ipad[5];
  u32  opad[5];
  u32  dgst[32];
  u32  out[32];
} pbkdf2_sha1_tmp_t;

typedef struct zfs_crypto {
  u32 version;
  u32 iterations;
  u32 salt[2];
  u32 mac[4];
  u64 guid;
  u32 master_key[8];
  u32 ddoobj;
  u32 iv[3];
  u32 refcount;
  u32 suite;
  u32 hmac_key[16];
} zfs_crypto_t;

static const char *SIGNATURE_ZFS = "$zfs$";

char *module_jit_build_options (MAYBE_UNUSED const hashconfig_t *hashconfig, MAYBE_UNUSED const user_options_t *user_options, MAYBE_UNUSED const user_options_extra_t *user_options_extra, MAYBE_UNUSED const hashes_t *hashes, MAYBE_UNUSED const hc_device_param_t *device_param)
{
  char *jit_build_options = NULL;

  // Extra treatment for Apple systems
  if (device_param->opencl_platform_vendor_id == VENDOR_ID_APPLE)
  {
    return jit_build_options;
  }

  // HIP
  if (device_param->opencl_device_vendor_id == VENDOR_ID_AMD_USE_HIP)
  {
    hc_asprintf (&jit_build_options, "-D _unroll");
  }

  // ROCM
  if ((device_param->opencl_device_vendor_id == VENDOR_ID_AMD) && (device_param->has_vperm == true))
  {
    hc_asprintf (&jit_build_options, "-D _unroll");
  }

  return jit_build_options;
}

int module_hash_decode (MAYBE_UNUSED const hashconfig_t *hashconfig, MAYBE_UNUSED void *digest_buf, MAYBE_UNUSED salt_t *salt, MAYBE_UNUSED void *esalt_buf, MAYBE_UNUSED void *hook_salt_buf, MAYBE_UNUSED hashinfo_t *hash_info, const char *line_buf, MAYBE_UNUSED const int line_len)
{
  zfs_crypto_t *zfs = (zfs_crypto_t *) esalt_buf;
  u32 *digest = (u32 *) digest_buf;

  hc_token_t token;
  memset(&token, 0, sizeof(hc_token_t));

  token.token_cnt  = 13;
  token.signatures_cnt = 1;
  token.signatures_buf[0] = SIGNATURE_ZFS;

  token.len[0]     = 5;
  token.attr[0]    = TOKEN_ATTR_FIXED_LENGTH | TOKEN_ATTR_VERIFY_SIGNATURE;

  token.sep[1]     = '*';
  token.len[1]     = 1;
  token.attr[1]    = TOKEN_ATTR_FIXED_LENGTH | TOKEN_ATTR_VERIFY_DIGIT;

  token.sep[2]     = '*';
  token.len[2]     = 6;
  token.attr[2]    = TOKEN_ATTR_FIXED_LENGTH | TOKEN_ATTR_VERIFY_DIGIT;

  token.sep[3]     = '*';
  token.len[3]     = 8;
  token.attr[3]    = TOKEN_ATTR_FIXED_LENGTH | TOKEN_ATTR_VERIFY_HEX;

  token.sep[4]     = '*';
  token.len[4]     = 32;
  token.attr[4]    = TOKEN_ATTR_FIXED_LENGTH | TOKEN_ATTR_VERIFY_HEX;

  token.sep[5]     = '*';
  token.len[5]     = 16;
  token.attr[5]    = TOKEN_ATTR_FIXED_LENGTH | TOKEN_ATTR_VERIFY_HEX;

  token.sep[6]     = '*';
  token.len[6]     = 64;
  token.attr[6]    = TOKEN_ATTR_FIXED_LENGTH | TOKEN_ATTR_VERIFY_HEX;

  token.sep[7]     = '*';
  token.len[7]     = 2;
  token.attr[7]    = TOKEN_ATTR_FIXED_LENGTH | TOKEN_ATTR_VERIFY_HEX;

  token.sep[8]     = '*';
  token.len[8]     = 24;
  token.attr[8]    = TOKEN_ATTR_FIXED_LENGTH | TOKEN_ATTR_VERIFY_HEX;

  token.sep[9]     = '*';
  token.len[9]     = 1;
  token.attr[9]    = TOKEN_ATTR_FIXED_LENGTH | TOKEN_ATTR_VERIFY_DIGIT;

  token.sep[10]    = '*';
  token.len[10]    = 1;
  token.attr[10]   = TOKEN_ATTR_FIXED_LENGTH | TOKEN_ATTR_VERIFY_DIGIT;

  token.sep[11]    = '*';
  token.len[11]    = 128;
  token.attr[11]   = TOKEN_ATTR_FIXED_LENGTH | TOKEN_ATTR_VERIFY_HEX;

  const int rc_tokenizer = input_tokenizer((const u8 *)line_buf, line_len, &token);
  if (rc_tokenizer != PARSER_OK) return rc_tokenizer;

  // Parse all components
  zfs->version     = hc_strtoul((char *)token.buf[1], NULL, 10);
  zfs->iterations  = hc_strtoul((char *)token.buf[2], NULL, 10);
  salt->salt_iter  = zfs->iterations - 1;

  // Salt (64-bit)
  salt->salt_buf[0] = hex_to_u32((u8 *)token.buf[3] + 0);
  salt->salt_buf[1] = hex_to_u32((u8 *)token.buf[3] + 8);
  salt->salt_len = 8;

  // MAC
  hex_to_u32_buffer((const u8 *)token.buf[4] + 0, &digest[0], 1);
  hex_to_u32_buffer((const u8 *)token.buf[4] + 8, &digest[1], 1);
  hex_to_u32_buffer((const u8 *)token.buf[4] + 16, &digest[2], 1);
  hex_to_u32_buffer((const u8 *)token.buf[4] + 24, &digest[3], 1);

  // GUID
  zfs->guid = hex_to_u64((u8 *)token.buf[5]);

  // Master Key
  for (int i = 0; i < 8; i++)
    hex_to_u32_buffer((const u8 *)token.buf[6] + (i * 8), &zfs->master_key[i], 1);
  //hex_to_u32_buffer((u8 *)token.buf[6] + (i * 8), 8, &zfs->master_key[i]);

  // DDOBJ
  zfs->ddoobj = hex_to_u32((u8 *)token.buf[7]);

  // IV (12 bytes)
  hex_to_u32_buffer((const u8 *)token.buf[8] + 0, &zfs->iv[0], 1);
  hex_to_u32_buffer((const u8 *)token.buf[8] + 8, &zfs->iv[1], 1);
  hex_to_u32_buffer((const u8 *)token.buf[8] + 16, &zfs->iv[2], 1);

  // Remaining parameters
  zfs->refcount = hc_strtoul((char *)token.buf[9], NULL, 10);
  zfs->suite    = hc_strtoul((char *)token.buf[10], NULL, 10);

  // HMAC Key
  for (int i = 0; i < 16; i++)
    hex_to_u32_buffer((const u8 *)token.buf[11] + (i * 8), &zfs->hmac_key[i], 1);

  return PARSER_OK;
}

int module_hash_encode (MAYBE_UNUSED const hashconfig_t *hashconfig, MAYBE_UNUSED const void *digest_buf, MAYBE_UNUSED const salt_t *salt, MAYBE_UNUSED const void *esalt_buf, MAYBE_UNUSED const void *hook_salt_buf, MAYBE_UNUSED const hashinfo_t *hash_info, char *line_buf, MAYBE_UNUSED const int line_size)
{
  const zfs_crypto_t *zfs = (const zfs_crypto_t *) esalt_buf;
  const u32 *digest = (const u32 *) digest_buf;

  char tmp_salt[9]    = { 0 };
  char tmp_mac[33]    = { 0 };
  char tmp_guid[17]   = { 0 };
  char tmp_mkey[65]   = { 0 };
  char tmp_ddoobj[3]  = { 0 };
  char tmp_iv[25]     = { 0 };
  char tmp_hmac[129]  = { 0 };

  u32_to_hex (salt->salt_buf[0], (u8 *) tmp_salt + 0);
  u32_to_hex (salt->salt_buf[1], (u8 *) tmp_salt + 8);

  u32_to_hex (digest[0], (u8 *) tmp_mac + 0);
  u32_to_hex (digest[1], (u8 *) tmp_mac + 8);
  u32_to_hex (digest[2], (u8 *) tmp_mac + 16);
  u32_to_hex (digest[3], (u8 *) tmp_mac + 24);

  u64_to_hex (zfs->guid, (u8 *) tmp_guid);

  for (int i = 0; i < 8; i++)
    u32_to_hex (zfs->master_key[i], (u8 *) tmp_mkey + (i * 8));

  u32_to_hex (zfs->ddoobj, (u8 *) tmp_ddoobj);

  u32_to_hex (zfs->iv[0], (u8 *) tmp_iv + 0);
  u32_to_hex (zfs->iv[1], (u8 *) tmp_iv + 8);
  u32_to_hex (zfs->iv[2], (u8 *) tmp_iv + 16);

  for (int i = 0; i < 16; i++)
    u32_to_hex (zfs->hmac_key[i], (u8 *) tmp_hmac + (i * 8));

  return snprintf (line_buf, line_size,
    "%s%u*%u*%s*%s*%s*%s*%s*%s*%u*%u*%s",
    SIGNATURE_ZFS,
    zfs->version,
    zfs->iterations,
    tmp_salt,
    tmp_mac,
    tmp_guid,
    tmp_mkey,
    tmp_ddoobj,
    tmp_iv,
    zfs->refcount,
    zfs->suite,
    tmp_hmac
  );
}
 
void module_init (module_ctx_t *module_ctx)
{
  module_ctx->module_context_size             = MODULE_CONTEXT_SIZE_CURRENT;
  module_ctx->module_interface_version        = MODULE_INTERFACE_VERSION_CURRENT;

  module_ctx->module_attack_exec              = module_attack_exec;
  module_ctx->module_benchmark_esalt          = MODULE_DEFAULT;
  module_ctx->module_benchmark_hook_salt      = MODULE_DEFAULT;
  module_ctx->module_benchmark_mask           = MODULE_DEFAULT;
  module_ctx->module_benchmark_charset        = MODULE_DEFAULT;
  module_ctx->module_benchmark_salt           = MODULE_DEFAULT;
  module_ctx->module_build_plain_postprocess  = MODULE_DEFAULT;
  module_ctx->module_deep_comp_kernel         = MODULE_DEFAULT;
  module_ctx->module_deprecated_notice        = MODULE_DEFAULT;
  module_ctx->module_dgst_pos0                = module_dgst_pos0;
  module_ctx->module_dgst_pos1                = module_dgst_pos1;
  module_ctx->module_dgst_pos2                = module_dgst_pos2;
  module_ctx->module_dgst_pos3                = module_dgst_pos3;
  module_ctx->module_dgst_size                = module_dgst_size;
  module_ctx->module_dictstat_disable         = MODULE_DEFAULT;
  module_ctx->module_esalt_size = (u64 (*)(const hashconfig_t *, const user_options_t *, const user_options_extra_t *))sizeof(zfs_crypto_t);
  module_ctx->module_tmp_size = (u64 (*)(const hashconfig_t *, const user_options_t *, const user_options_extra_t *))sizeof(pbkdf2_sha1_tmp_t);
  module_ctx->module_extra_buffer_size        = MODULE_DEFAULT;
  module_ctx->module_extra_tmp_size           = MODULE_DEFAULT;
  module_ctx->module_extra_tuningdb_block     = MODULE_DEFAULT;
  module_ctx->module_forced_outfile_format    = MODULE_DEFAULT;
  module_ctx->module_hash_binary_count        = MODULE_DEFAULT;
  module_ctx->module_hash_binary_parse        = MODULE_DEFAULT;
  module_ctx->module_hash_binary_save         = MODULE_DEFAULT;
  module_ctx->module_hash_decode_postprocess  = MODULE_DEFAULT;
  module_ctx->module_hash_decode_potfile      = MODULE_DEFAULT;
  module_ctx->module_hash_decode_zero_hash    = MODULE_DEFAULT;
  module_ctx->module_hash_decode              = module_hash_decode;
  module_ctx->module_hash_encode_status       = MODULE_DEFAULT;
  module_ctx->module_hash_encode_potfile      = MODULE_DEFAULT;
  module_ctx->module_hash_encode              = module_hash_encode;
  module_ctx->module_hash_init_selftest       = MODULE_DEFAULT;
  module_ctx->module_hash_mode                = MODULE_DEFAULT;
  module_ctx->module_hash_category            = module_hash_category;
  module_ctx->module_hash_name                = module_hash_name;
  module_ctx->module_hashes_count_min         = MODULE_DEFAULT;
  module_ctx->module_hashes_count_max         = MODULE_DEFAULT;
  module_ctx->module_hlfmt_disable            = MODULE_DEFAULT;
  module_ctx->module_hook_extra_param_size    = MODULE_DEFAULT;
  module_ctx->module_hook_extra_param_init    = MODULE_DEFAULT;
  module_ctx->module_hook_extra_param_term    = MODULE_DEFAULT;
  module_ctx->module_hook12                   = MODULE_DEFAULT;
  module_ctx->module_hook23                   = MODULE_DEFAULT;
  module_ctx->module_hook_salt_size           = MODULE_DEFAULT;
  module_ctx->module_hook_size                = MODULE_DEFAULT;
  module_ctx->module_jit_build_options        = MODULE_DEFAULT;
  module_ctx->module_jit_cache_disable        = MODULE_DEFAULT;
  module_ctx->module_kernel_accel_max         = MODULE_DEFAULT;
  module_ctx->module_kernel_accel_min         = MODULE_DEFAULT;
  module_ctx->module_kernel_loops_max         = MODULE_DEFAULT;
  module_ctx->module_kernel_loops_min         = MODULE_DEFAULT;
  module_ctx->module_kernel_threads_max       = MODULE_DEFAULT;
  module_ctx->module_kernel_threads_min       = MODULE_DEFAULT;
  module_ctx->module_kern_type                = module_kern_type;
  module_ctx->module_kern_type_dynamic        = MODULE_DEFAULT;
  module_ctx->module_opti_type                = module_opti_type;
  module_ctx->module_opts_type                = module_opts_type;
  module_ctx->module_outfile_check_disable    = MODULE_DEFAULT;
  module_ctx->module_outfile_check_nocomp     = MODULE_DEFAULT;
  module_ctx->module_potfile_custom_check     = MODULE_DEFAULT;
  module_ctx->module_potfile_disable          = MODULE_DEFAULT;
  module_ctx->module_potfile_keep_all_hashes  = MODULE_DEFAULT;
  module_ctx->module_pwdump_column            = MODULE_DEFAULT;
  module_ctx->module_pw_max                   = module_pw_max;
  module_ctx->module_pw_min                   = module_pw_min;
  module_ctx->module_salt_max                 = MODULE_DEFAULT;
  module_ctx->module_salt_min                 = MODULE_DEFAULT;
  module_ctx->module_salt_type                = module_salt_type;
  module_ctx->module_separator                = MODULE_DEFAULT;
  module_ctx->module_st_hash                  = module_st_hash;
  module_ctx->module_st_pass                  = module_st_pass;
  module_ctx->module_unstable_warning         = MODULE_DEFAULT;
  module_ctx->module_warmup_disable           = MODULE_DEFAULT;
}